name: DebugBuild

# 実行する時間(masterブランチにプッシュされた時)
on:
  push:
    branches:
    - maater
#ビルド内容
env:
  # リポジトリのルートディレクトリを基点としたソリューションファイルのパス
  SOLUTION_FILE_PATH: Project/CG2_Project.sln
  # Visual Studio の構成(Debug)
  CONFIGURATUIN: Debug
# ビルドをする
jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
          
      - name: Build
        run: |
            msbuild ${{env.SOLUTION_FILE_PATH}}/p:Pratform=x64,Configuration=$ {{env.CONFIGURATION}}
            jobs.<job_id>.steps[*].run:
